# Generated by Django 4.2.10 on 2024-03-13 18:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=1000, verbose_name='Место выполнения привычки')),
                ('action_time', models.DateTimeField(blank=True, null=True, verbose_name='Время действия')),
                ('action', models.CharField(max_length=1000, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Повторять каждый <номер> день')),
                ('reward', models.CharField(blank=True, max_length=500, null=True, verbose_name='Вознаграждение')),
                ('execution_time', models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на исполнение привычки, сек')),
                ('is_public', models.BooleanField(default=False, verbose_name='Открыта для всех')),
                ('associated_with', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pleasant', to='habitsapp.habit', verbose_name='Связанная приятная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
